#!/bin/sh

if [ "$1" == "" ]; then
    echo "app name must not be empty\n"
    echo "usage:"
    echo "\tsh generate APPNAME"
    exit
fi

PKGNAME=`echo $1 | sed "s/-/./g"`
PKGDIR=`echo $1 | sed "s/-/\//g"`

git clone git@gitee.com:pysongyg/app_demo.git
mv app_demo $1

echo "now generating new project withe name $1"
rm -fr ./$1/.git
rm -fr ./$1/core/src/main/resources/special
mkdir -p ./$1/client/src/main/java/com/jhtech/$PKGDIR
mkdir -p ./$1/core/src/main/java/com/jhtech/$PKGDIR
mv -v ./$1/client/src/main/java/com/jhtech/appdemo/* ./$1/client/src/main/java/com/jhtech/$PKGDIR
mv -v ./$1/core/src/main/java/com/jhtech/appdemo/* ./$1/core/src/main/java/com/jhtech/$PKGDIR

rm -fr ./$1/core/src/main/java/com/jhtech/appdemo
rm -fr ./$1/client/src/main/java/com/jhtech/appdemo

find ./$1 -type f -name "*.java" -exec sed -i "s/appdemo/$PKGNAME/g" {} \;
find ./$1 -type f -name "*.properties" -exec sed -i "s/appdemo/$1/g" {} \;
find ./$1 -type f -name "app.xml" -exec sed -i "s/appdemo/$PKGNAME/g" {} \;
find ./$1 -type f -name "pom.xml" -exec sed -i "s/appdemo/$1/g" {} \;
find ./$1 -type f -name "assembly.xml" -exec sed -i "s/appdemo/$1/g" {} \;

echo "all done! enjoy"

